[tool.poetry]
name = "server"
version = "0.1.0"
description = "Greate Route For Your Trip"
authors = ["chado13 <geaya13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dotenv-python = "^0.0.1"
openai = "^1.16.2"
fastapi = "^0.110.1"
pydantic-settings = "^2.2.1"
uvicorn = "^0.29.0"
requests = "^2.32.3"
jinja2 = "^3.1.4"


[tool.poetry.group.dev.dependencies]
ruff = "^0.3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
